run:
  concurrency: 3
  deadline: 30s
  tests: true

output:
  format: tab
  print-issued-lines: true
  print-linter-name: true
  sort-results: false

linters:
  enable-all: true
  disable:
    - wrapcheck
    - tagliatelle
    - exhaustivestruct
    - gci
    - golint
    - interfacer
    - scopelint
    - maligned
    - gochecknoglobals
    - revive
    - goerr113
    - gochecknoinits
    - exhaustive

linters-settings:
  lll:
    line-length: 140
  gosec:
    excludes:
      - G306
